
import io
import base64
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Image as RLImage, Table, TableStyle
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle


def generate_pdf_report(analysis) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.6 * inch)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "TitleStyle", parent=styles["Title"], fontSize=18, textColor=HexColor("#1e3a8a")
    )
    section_style = ParagraphStyle(
        "SectionStyle", parent=styles["Heading2"], fontSize=12, textColor=HexColor("#1e3a8a"), spaceBefore=14
    )
    body_style = styles["BodyText"]
    disclaimer_style = ParagraphStyle(
        "DisclaimerStyle", parent=styles["BodyText"], fontSize=8, textColor=HexColor("#b91c1c")
    )

    elements = []

    elements.append(Paragraph("Medical Vision Assistant — AI Research Report", title_style))
    elements.append(Paragraph(f"Generated: {analysis.created_at.strftime('%Y-%m-%d %H:%M UTC')}", body_style))
    elements.append(Spacer(1, 12))

    # Heatmap image, if present
    if analysis.heatmap:
        try:
            header, encoded = analysis.heatmap.split(",", 1)
            img_bytes = base64.b64decode(encoded)
            img_buffer = io.BytesIO(img_bytes)
            elements.append(RLImage(img_buffer, width=3 * inch, height=3 * inch))
            elements.append(Spacer(1, 10))
        except Exception:
            pass

    # Prediction summary table
    prob_rows = [["Class", "Probability"]] + [
        [k, f"{v}%"] for k, v in analysis.probabilities.items()
    ]
    table = Table(prob_rows, colWidths=[2.5 * inch, 2 * inch])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), HexColor("#dbeafe")),
        ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#cbd5e1")),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(Paragraph("Prediction Summary", section_style))
    elements.append(Paragraph(f"<b>Disease:</b> {analysis.disease} &nbsp;&nbsp; <b>Confidence:</b> {analysis.confidence}%", body_style))
    elements.append(Spacer(1, 6))
    elements.append(table)

    elements.append(Paragraph("Findings", section_style))
    elements.append(Paragraph(analysis.report_findings or "N/A", body_style))

    elements.append(Paragraph("Risk Assessment", section_style))
    elements.append(Paragraph(f"Risk level: {analysis.report_risk_level or 'N/A'}", body_style))

    elements.append(Paragraph("Recommendation", section_style))
    elements.append(Paragraph(analysis.report_recommendation or "N/A", body_style))

    elements.append(Spacer(1, 20))
    elements.append(Paragraph(
        "DISCLAIMER: This report was generated by an AI research prototype for "
        "educational and portfolio purposes only. It is NOT a certified medical "
        "diagnosis and must NOT be used for real patient care decisions. Always "
        "consult a licensed healthcare professional.",
        disclaimer_style
    ))

    doc.build(elements)
    buffer.seek(0)
    return buffer.read()